name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Upgrade pip version
        run: |
          python -m pip install -U pip

      - name: Install requirements
        run: |
          python -m pip install --group dev

      - name: Lint
        run: |
          python -m ruff check

      - name: Run Unit Tests and generate coverage report
        run: |
          python -m unittest discover -v

      - name: Run package creation
        run: |
          python -m build
