# GitHub CI build pipeline
name: Pycomposefile CI build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.11"
          - python-version: "3.12"
          - python-version: "3.13"
          - python-version: "3.10"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m venv env
          source env/bin/activate
          python -m pip install -U pip

      - name: Install requirements
        run: |
          source env/bin/activate
          #python -m pip install coverage
          python -m pip install -r requirements.txt

      - name: Lint
        run: |
          source env/bin/activate
          python -m flake8 -v .

      - name: Run Unit Tests and generate coverage report
        run: |
          source env/bin/activate
          python -m unittest discover -v
          #coverage run -m unittest
          #coverage report
          #coverage html

      - name: Run package creation
        run: |
          source env/bin/activate
          python -m build --sdist --wheel --outdir dist/ .
