name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pypa/build
        run: |
          python -m pip install -r requirements.txt

      - name: Build a binary wheel and a source tarball
        run: |
          sed -i 's/^version = ".*"$/version = "'${GITHUB_REF_NAME#v}'"/' pyproject.toml
          python -m build

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
